version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx
      - ./nginx-logs:/var/log/nginx
      - ./static-files:/usr/share/nginx/html